#+OPTIONS: ^:nil

* Modest
Musical harmony library for Lua.

* Documentation
** Chord
*** Methods

- fromstring(string) -> Chord
  - Parses a string and returns a Chord object.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local chord = Chord.fromstring("Cmaj7")
    print(chord)
    #+end_src

- transpose(self, interval) -> Chord
  - Returns a new Chord transposed by the given interval.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local chord = Chord.fromstring("C6/9")
    local transposed = chord:transpose(Interval.new(5))
    print(transposed)
    #+end_src

- transpose_down(self, interval) -> Chord
  - Similar to transpose, returns a chord transposed down by the given interval.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local chord = Chord.fromstring("Ab9")
    local transposed_down = chord:transpose_down(Interval.new(5))
    print(transposed_down)
    #+end_src

- notes(self, octave=nil) -> [Note]
  - Returns the notes that make up the chord. Optionally, specify the octave of the root note.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local chord = Chord.fromstring("F#")
    local notes = chord:notes(4)
    for _, note in ipairs(notes) do print(note) end
    #+end_src

- numeric(self) -> [int]
  - Converts the chord into a numeric representation, with each note represented as the number of semitones from the C of the chord's root octave.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local chord = Chord.fromstring("C/Bb")
    local numeric = chord:numeric()
    print(table.concat(numeric, ", "))
    #+end_src

    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local chord = Chord.fromstring("G9")
    local numeric = chord:numeric()
    print(table.concat(numeric, ", "))
    #+end_src

- tostring(self, ascii=nil) -> string
  - Converts the chord into a string. By default accidental will be represented with special Unicode characters ('â™¯' for sharp, 'â™­' for flat, 'ð„ª' for double sharp, 'ð„«' for double flat). Pass a true value as a parameter to get an ASCII representation ('#' for sharp, 'b' for flat, 'x' for double sharp, 'bb' for double flat).
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
      local chord = Chord.fromstring("C#maj7")
      print(chord:tostring())
      print(chord:tostring(true)
    #+end_src

- toascii(self) -> string
  - Shorthand for chord:tostring(true). Returns the chord as a string with ASCII representations for accidentals.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
      local chord = Chord.fromstring("C#maj7")
      print(chord:toascii())
    #+end_src

** Interval
*** Methods

- fromstring(string) -> Interval
  - Parses a string and returns an Interval object. Examples: 
    - "m3" = minor third
    - "P4" = perfect fourth
    - "A5" = augmented fifth
    - "d7" = diminished seventh
    - "M6" = major sixth.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local interval = Interval.fromstring("P4")
    print(interval)
    #+end_src

- new(size, quality="perefect") -> Note
  - Creates a new Interval object. Size should be an integer, and quality should be a string (valid options are "dim", "aug", "min", "maj", "perfect"). The method raises an error if the interval is invalid.
  - Examples:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
      local interval = Interval.new(3, "aug")
      print(interval)
    #+end_src

    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
      local interval = Interval.new(11, "maj")
      print(interval)
    #+end_src

    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
      local interval = Interval.new(5)
      print(interval)
    #+end_src

    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
      local _, err = pcall(function() Interval.new(5, "min") end)
      print(err)
    #+end_src

- identify(note1, note2) -> Interval
  - Identifies the interval between two notes.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local C = Note.fromstring("C")
    local F = Note.fromstring("F")
    local interval = Interval.identify(C, F)
    print(interval)
    #+end_src

- semitones(self) -> int
  - Returns the number of semitones in the interval.
  - Examples:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local interval = Interval.fromstring("M3")
    print(interval:semitones())
    #+end_src

- tostring(self) -> string
  - Converts the interval into a string representation.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local interval = Interval.new(6, "min")
    print(interval)
    #+end_src

** Note
*** Methods

- fromstring(string) -> Note
  - Parses a string and returns a Note object.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local note = Note.fromstring("C#4")
    print(note)
    #+end_src

- new(tone, accidental=0, octave=nil) -> Note
  - Creates a new Note object. The tone should be a capital letter (e.g., "C"). The accidental should be a numeric value (e.g., -1 for flat, 1 for sharp). The octave is optional.
  - Examples:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local note = Note.new("D", 1, 5)
    print(note)
    #+end_src

    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local note = Note.new("B", -2)
    print(note)
    #+end_src

- transpose(self, interval) -> Note
  - Returns a new note transposed by the given interval.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local note = Note.fromstring("C4")
    local transposed = note:transpose(Interval.new(4))
    print(transposed)
    #+end_src

- transpose_down(self, interval) -> Note
  - Returns a new note transposed down by the given interval.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local note = Note.fromstring("C4")
    local transposed_down = note:transpose_down(Interval.new(3, "min"))
    print(transposed_down)
    #+end_src

- pitch_class(self) -> int
  - Returns a number from 0 to 11 representing the pitch class of the note (e.g., C=0, Câ™¯/Dâ™­=1, ..., B=11).
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
    local note = Note.fromstring("G")
    print(note:pitch_class())
    #+end_src

- tostring(self, ascii) -> string
- toascii(self) -> string
  - Works similarly to the Chord methods of the same name.
  - Example:
    #+begin_src lua :prologue "l = require 'modest' Chord, Interval, Note = l.Chord, l.Interval, l.Note" :results output
      local note = Note.fromstring("D#4")
      print(note:tostring())
      print(note:tostring(true))
      print(note:toascii())
    #+end_src

